[package]
name = "glifparser"
version = "0.0.0"
authors = ["Fredrick Brennan <copypaste@kittens.ph>"]
edition = "2018"

[dependencies]
xmltree = "0.10.3"
log = "0.4"
kurbo = "0.8"
trees = "0.4"

# Our submodules
integer_or_float = { git = "https://github.com/MFEK/integer_or_float.rlib" }
